version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_producer
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
